dist: xenial   # required for Python >= 3.7
language: python
sudo: required

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432

cache:
  directories:
    - $HOME/.cache/pip

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log

python:
  - "3.6"

before_install:
  - pip3 install --upgrade pip

install:
  - pip3 install -r requirements.txt

before_script:
  - psql -U postgres -c "CREATE DATABASE pmr"
  - psql -U postgres -c "CREATE USER admin WITH PASSWORD 'admin'"
  - psql -U postgres -c "ALTER ROLE admin SET client_encoding TO 'utf8'"
  - psql -U postgres -c "ALTER ROLE admin SET default_transaction_isolation TO 'read committed'"
  - psql -U postgres -c "ALTER ROLE admin SET timezone TO 'UTC'"
  - psql -U postgres -c "ALTER USER admin CREATEDB"
  - psql -U postgres -c "ALTER DATABASE pmr OWNER TO admin"
  - mkdir tests/testdata
  - cd tests/testdata
  - wget https://www.dropbox.com/s/1bnxg32zvgjv0pl/compareImage.jpeg
  - wget https://www.dropbox.com/s/1bnxg32zvgjv0pl/compareImage.jpeg
  - wget https://www.dropbox.com/s/x3qpga9gc4ifamn/t1.png
  - wget https://www.dropbox.com/s/l5t09lp8u4ok593/t2.jpeg
  - wget https://www.dropbox.com/s/hzlpo74tk0xwzzh/t3.jpeg
  - wget https://www.dropbox.com/s/lni50cgunua5mij/test1.mp4
  - wget https://www.dropbox.com/s/wm3llx0ydbnq8mn/test2.mp4
  - wget https://www.dropbox.com/s/ato4fie6k3lmctu/test3.mp4
  - wget https://www.dropbox.com/s/ifd7254x29oxjze/test4.mp4
  - wget https://www.dropbox.com/s/iwtgwz24eipd629/obj1.mp4
  - wget https://www.dropbox.com/s/ull2tqlou1p8l16/obj2.mp4
  - wget https://www.dropbox.com/s/3w5ghr5jj6opr58/scene1.mp4
  - wget https://www.dropbox.com/s/ij5hj4hznczvfcw/text.mp4
  - cd ../..
  - export DJANGO_SETTINGS_MODULE="Rekognition.settings"

script:
  - flake8 .
  - coverage run -m tests.test_views
  - coverage run -m tests.test_models

after_success:
  - coveralls
