# Generated by Django 2.2.1 on 2019-06-12 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inputimage',
            name='imagefile',
        ),
        migrations.RemoveField(
            model_name='inputvideo',
            name='videofile',
        ),
        migrations.AlterField(
            model_name='inputimage',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='inputvideo',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
