# Generated by Django 2.2.1 on 2020-05-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0002_remove_similarfaceinimage_fileurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputimage',
            old_name='isProcessed',
            new_name='is_processed',
        ),
        migrations.RenameField(
            model_name='inputvideo',
            old_name='isProcessed',
            new_name='is_processed',
        ),
        migrations.RenameField(
            model_name='namesuggested',
            old_name='suggestedName',
            new_name='suggested_name',
        ),
    ]
