# Generated by Django 2.2.1 on 2019-06-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0004_inputembed'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputembed',
            name='fileurl',
            field=models.CharField(default='/Users/amit/GitHub/Rekognition/media/face/<django.db.models.fields.UUIDField>.jpg', editable=False, max_length=100),
        ),
    ]
