# Generated by Django 2.2.1 on 2019-06-22 07:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0006_auto_20190622_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputembed',
            name='fileurl',
            field=models.CharField(default='media/face/b803c097-b3a8-4f29-b575-9f89ec4e75c2.jpg', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='inputembed',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b803c097-b3a8-4f29-b575-9f89ec4e75c2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
