# Generated by Django 2.2.1 on 2019-06-22 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0007_auto_20190622_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputembed',
            name='fileurl',
            field=models.CharField(default='/media/face/0334f9be-a85d-4a22-94fb-82d060ff59d2.jpg', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='inputembed',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0334f9be-a85d-4a22-94fb-82d060ff59d2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
