# Generated by Django 2.2.1 on 2019-06-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0008_auto_20190622_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputembed',
            name='fileurl',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='inputembed',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
