# Generated by Django 2.2.1 on 2019-06-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0009_auto_20190622_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputimage',
            name='isProcessed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inputvideo',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
