# Generated by Django 2.2.1 on 2019-07-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0012_namesuggested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputembed',
            name='id',
            field=models.CharField(editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
