# Generated by Django 2.2.1 on 2019-07-09 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0013_auto_20190709_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namesuggested',
            old_name='feedBackId',
            new_name='feedBack',
        ),
    ]
