# Generated by Django 2.2.1 on 2019-07-09 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapi', '0014_auto_20190709_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='namesuggested',
            old_name='feedBack',
            new_name='feedback',
        ),
    ]
